# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IdRLBQLxj1amYRF2Fvlk2_Cb3JGMPWnP
"""

while True:
  print("calculadora")
  a = float(input("digite um numero: "))
  b = float(input("digite outro numero: "))
  print("escolha a porra ai")
  print("1 - soma")
  print("2 - subtração")
  print("3 - multiplicação")
  print('4 - divisão')
  op = input("digite o numero da sua escolha: ")
  if op == "1":
   print("resultado: " , a + b)
  elif op == "2":
   print("resultado: " , a - b)
  elif op == "3":
   print("resultado: " , a * b)
  elif op == "4":

      if b != 0:
       print("resultado: " , a / b)
      else:
       print("erro: divisão por zero")
  else:
    print("operação invalída")

  print("quer continuar")
  print("1 - sim")
  print("2 - não")
  sair = input("digite essa pora: ")

  if sair == "2":
    print("encerrar progama.")
    break